apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-token-provider-app
  labels:
    app: jwt-token-provider-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : jwt-token-provider-app
  template:
    metadata:
      labels:
        app: jwt-token-provider-app
    spec:
      containers:
      - name: jwt-token-provider-app
        image: zmhtet/jwt-token-provider:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9005

---

kind: Service
apiVersion: v1
metadata:
  name:  jwt-token-provider-svc
spec:
  selector:
    app:  jwt-token-provider-app
  ports:
  - port:  9005
    targetPort:  9005
