apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-app
  labels:
    app: notification-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : notification-service-app
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
      - name: notification-service-app
        image: zmhtet/notification-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9004

---

kind: Service
apiVersion: v1
metadata:
  name:  notification-service-svc
spec:
  selector:
    app:  notification-service-app
  ports:
  - port:  9004
    targetPort:  9004
